on:
  push:
    tags:
      - 'update-blue-from*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set curent version env
        uses: actions/github-script@0.9.0
        with:
          script: |
            const tag = ${{github.ref_name}}
            const currentVersion = tag.split('-')[0]
            core.setOutput('currentVersion', currentVersion)
      - name: Display version
        run: |
          echo echo "${{steps.get-currentVersion.outputs.currentVersion}}"