on:
  push:
    tags:
      - 'update-blue-from*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set tag env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set curent version env
        uses: actions/github-script@0.9.0
        with:
          script: |
            const currentVersion = $TAG.value.split('-')[3].substring(1)
            core.setOutput('currentVersion', currentVersion)
      - name: Display version
        run: |
          echo echo "${{steps.get-currentVersion.outputs.currentVersion}}"