on:
  push:
    tags:
      - 'update-blue-from*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set tag env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set curent version env
        run: echo "CURRENT_VERSION=${TAG}" >> $GITHUB_ENV
      - name: Display version
        run: |
          echo $CURRENT_VERSION